name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HELM_VERSION: [3.5.0]
    services:
      minio:
        image: minio/minio:edge-cicd
        ports:
          - 9000:9000
    env:
      GOPATH: ${{ github.workspace }}/go
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: ${{ matrix.HELM_VERSION }}
    - run: |
           if [ "${{ matrix.HELM_VERSION }}" == "2.17.0" ]; then
             helm init --client-only
           else
             helm repo add stable https://charts.helm.sh/stable
           fi
           make deps
           make build
           make test-unit
           sed -i "/^hooks:/,+2 d" plugin.yaml
           helm install .
           make test-e2e
      env:
        AWS_ACCESS_KEY_ID: minioadmin
        AWS_SECRET_ACCESS_KEY: minioadmin
        AWS_ENDPOINT: localhost:9000
        AWS_DISABLE_SSL: true
