name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HELM_VERSION: [2.17, 3.4, 3.5]
    services:
      minio:
        image: minio/minio:edge-cicd
        ports:
          - 9000:9000
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: ${matrix.HELM_VERSION}
    - name: Build
      run: make build
    - name: Unit Test
      run: make test
    - name: E2E Test
      run: make test
      env:
        AWS_ACCESS_KEY_ID: minioadmin
        AWS_SECRET_ACCESS_KEY: minioadmin
        AWS_ENDPOINT: localhost:9000
        AWS_DISABLE_SSL: true
