on:
  push:
    tags:
      - '*'

name: release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HELM_VERSION: [3.5.0]
    services:
      minio:
        image: minio/minio:edge-cicd
        ports:
          - 9000:9000
    env:
      GOPATH: ${{ github.workspace }}/go
      GO111MODULE: on
    steps:
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
